name: CI/CD

on:
  push:
    branches:
      - release

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Get the latest tag
      id: get_tag
      run: |
        latest_tag=$(git describe --tags --abbrev=0)
        major=$(echo $latest_tag | cut -d'.' -f1 | sed 's/v//')
        minor=$(echo $latest_tag | cut -d'.' -f2)
        new_minor=$((minor + 1))
        new_tag="v$major.$new_minor"
        echo "::set-output name=new_tag::$new_tag"
        
    - name: Create Git Tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag "${{ steps.get_tag.outputs.new_tag }}"
        git push origin HEAD:release --tags
        
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: refik/webhook-proxy
        tag_with_ref: true
        push: true
