name: CI/CD

on:
  push:
    branches:
      - release

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-tags: true
    
    - name: Fetch the tags
      run: |
        git fetch --unshallow --tags

    - name: Get the latest tag
      id: get_tag
      run: |
        latest_tag=$(git describe --tags --abbrev=0)
        major=$(echo $latest_tag | cut -d'.' -f1 | sed 's/v//')
        minor=$(echo $latest_tag | cut -d'.' -f2)
        new_minor=$((minor + 1))
        new_tag="v$major.$new_minor"
        echo "::set-output name=new_tag::$new_tag"
        
    - name: Create Git Tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag "${{ steps.get_tag.outputs.new_tag }}"
        git push origin HEAD:release --tags

    - name: Docker Meta
      uses: docker/metadata-action@v5
      with:
        images: |
          refik/webhook-proxy
        tags: |
          type=raw,value=latest
          type=semver,pattern={{major}}.{{minor}}
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
